const GAME_LEVELS = [
  {
    "id": 10,
    "name": "RootMatrix",
    "size": "room",
    "desc": "This is a test",
    "faces": {
      "face_back": [
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        null,
        "95"
      ],
      "face_left": [
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95"
      ],
      "face_right": [
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95"
      ],
      "face_top": [
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95",
        "95"
      ],
      "face_bottom": [
        "68",
        "68",
        "25",
        "68",
        "68",
        "19",
        "68",
        "24",
        "68",
        "68",
        "19",
        "68",
        "24",
        "19",
        "19",
        "95",
        "95",
        "24",
        "95",
        "95",
        "95",
        "95",
        "25",
        "95",
        "95"
      ]
    },
    "background": "9",
    "objects": [],
    "npc": [],
    "npcs": [
      {
        "n_id": 1,
        "sprite_id": 0,
        "left": 38,
        "top": 874,
        "z": 20,
        "rx": 0,
        "ry": 36,
        "rz": 0,
        "scale": 1,
        "portrait_left": -60,
        "portrait_top": -12,
        "portait_scaleX": 1,
        "dialogue": "Nice place to fish...",
        "portrait_scaleX": 1
      },
      {
        "n_id": 2,
        "sprite_id": 1,
        "left": 455,
        "top": 874,
        "z": -17,
        "rx": 0,
        "ry": 341,
        "rz": 0,
        "scale": 1,
        "portrait_left": -54,
        "portrait_top": 0,
        "portrait_scaleX": 1,
        "dialogue": "You're late.."
      }
    ],
    "treasure_boxes": [
      {
        "t_id": 1,
        "sprite_id": 0,
        "left": 115,
        "top": 876,
        "opened": true,
        "content_type": "weapon",
        "content_id": 13
      },
      {
        "t_id": 2,
        "sprite_id": 5,
        "left": 350,
        "top": 876,
        "opened": true,
        "content_type": "material",
        "content_id": 17
      }
    ],
    "enemy_encounters": [
      {
        "encounter_id": 0,
        "front_position": 2,
        "mid_1": 14,
        "mid_2": 14,
        "back_1": 6,
        "back_2": 1,
        "back_3": 6
      },
      {
        "encounter_id": 0,
        "front_position": 7,
        "mid_1": null,
        "mid_2": null,
        "back_1": null,
        "back_2": null,
        "back_3": null,
        "rate": "common"
      },
      {
        "encounter_id": 0,
        "front_position": null,
        "mid_1": 7,
        "mid_2": 7,
        "back_1": null,
        "back_2": 13,
        "back_3": null,
        "rate": "common"
      },
      {
        "encounter_id": 0,
        "front_position": null,
        "mid_1": 0,
        "mid_2": 0,
        "back_1": 3,
        "back_2": 2,
        "back_3": 3,
        "rate": "paradismic"
      }
    ],
    "landmarks": [
      {
        "landmark_id": 1,
        "sprite_id": 0,
        "left": 238,
        "top": 747,
        "exit_type": "down",
        "destination_type": "to_world_map",
        "destination_to": "teleport:61"
      }
    ]
  },
  {
    "id": 2,
    "name": "New Room",
    "size": "room",
    "desc": "This is a new room",
    "background": "1",
    "faces": {
      "face_back": [
        "53",
        "53",
        "53",
        "53",
        "53",
        "8",
        "8",
        "8",
        "8",
        "8",
        "95",
        "95",
        "95",
        "95",
        "95",
        "57",
        "57",
        "57",
        "57",
        "57"
      ],
      "face_left": [
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "57",
        "57",
        "57",
        "57",
        "57"
      ],
      "face_right": [
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "53",
        "57",
        "57",
        "57",
        "57",
        "57"
      ],
      "face_top": [
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51",
        "51"
      ],
      "face_bottom": [
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38"
      ]
    },
    "objects": [
      {
        "p_id": 1,
        "sprite_id": 25,
        "left": 43,
        "top": 877,
        "z": -30,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 2,
        "sprite_id": 24,
        "left": 53,
        "top": 853,
        "z": -11,
        "rx": 0,
        "ry": 52,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 3,
        "sprite_id": 11,
        "left": 482,
        "top": 596,
        "z": -228,
        "rx": 29,
        "ry": 0,
        "rz": 59,
        "scale": 1
      },
      {
        "p_id": 4,
        "sprite_id": 6,
        "left": 241,
        "top": 586,
        "z": -240,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 5,
        "sprite_id": 20,
        "left": 530,
        "top": 750,
        "z": 0,
        "rx": 0,
        "ry": 100,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 6,
        "sprite_id": 10,
        "left": 241,
        "top": 551,
        "z": 193,
        "rx": 99,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 7,
        "sprite_id": 22,
        "left": 377,
        "top": 881,
        "z": 230,
        "rx": 0,
        "ry": 316,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 8,
        "sprite_id": 25,
        "left": 230,
        "top": 884,
        "z": 400,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 9,
        "sprite_id": 21,
        "left": -46,
        "top": 739,
        "z": 131,
        "rx": 0,
        "ry": 84,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 10,
        "sprite_id": 11,
        "left": 80,
        "top": 603,
        "z": 400,
        "rx": 74,
        "ry": 157,
        "rz": 0,
        "scale": 1
      }
    ],
    "npc": [],
    "npcs": [],
    "treasure_boxes": [],
    "enemy_encounters": [],
    "landmarks": [
      {
        "landmark_id": 1,
        "sprite_id": 0,
        "left": 6,
        "top": 837,
        "exit_type": "down",
        "destination_type": "to_world_map",
        "destination_to": "teleport:821"
      }
    ]
  },
  {
    "id": 3,
    "name": "mid",
    "size": "mid",
    "desc": "a medium sized level",
    "background": "3",
    "faces": {
      "face_back": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "38"
      ],
      "face_left": [],
      "face_right": [],
      "face_top": [],
      "face_bottom": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "38",
        "38",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "38",
        "38",
        "38",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "38",
        "38",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "38",
        "38",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "38",
        "38"
      ]
    },
    "objects": [],
    "npcs": [
      {
        "n_id": 1,
        "sprite_id": 1,
        "left": -60,
        "top": 920,
        "z": 0,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1,
        "portrait_left": -51,
        "portrait_top": 0,
        "portrait_scaleX": 1,
        "dialogue": "Not Bad..."
      }
    ],
    "treasure_boxes": [],
    "enemy_encounters": [],
    "landmarks": []
  },
  {
    "id": 4,
    "name": "large",
    "size": "large",
    "desc": "a large sized level",
    "background": "12",
    "faces": {
      "face_back": [
        null,
        "45",
        null,
        null,
        "45",
        null,
        null,
        null,
        "45",
        "95",
        null,
        null,
        null,
        null,
        "45",
        null,
        null,
        null,
        null,
        null,
        null,
        "45",
        null,
        null,
        "45",
        null,
        null,
        null,
        "45",
        "95",
        "62",
        "62",
        "1",
        null,
        "45",
        null,
        null,
        null,
        null,
        null,
        null,
        "45",
        null,
        null,
        "45",
        null,
        null,
        null,
        "45",
        "95",
        "62",
        "62",
        "62",
        null,
        "45",
        null,
        null,
        null,
        null,
        null,
        null,
        "45",
        null,
        null,
        "45",
        "95",
        null,
        null,
        "45",
        "95",
        "62",
        "8",
        "62",
        null,
        "45",
        null,
        null,
        null,
        null,
        null,
        "60",
        null,
        null,
        "60",
        "60",
        null,
        null,
        null,
        null,
        "38",
        "38",
        "38",
        "38",
        "38",
        "38"
      ],
      "face_left": [],
      "face_right": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "95"
      ],
      "face_top": [
        null,
        null,
        null,
        null,
        null,
        "45",
        null,
        null,
        null,
        null,
        null,
        "45",
        null,
        null,
        null,
        "45",
        null,
        null,
        "45",
        null,
        null,
        null,
        null,
        null,
        null,
        "45",
        null,
        null,
        null,
        null,
        null,
        "45",
        null,
        null,
        null,
        "45",
        null,
        null,
        "45",
        null,
        null,
        null,
        null,
        null,
        null,
        "45",
        null,
        null,
        null,
        null,
        null,
        "45",
        null,
        null,
        null,
        "45",
        null,
        null,
        "45",
        null,
        null,
        null,
        null,
        null,
        null,
        "45",
        null,
        null,
        null,
        null,
        null,
        "45",
        null,
        null,
        null,
        "45",
        null,
        null,
        "45",
        null,
        null,
        null,
        null,
        null,
        null,
        "45",
        null,
        null,
        null,
        null,
        null,
        "45",
        null,
        null,
        null,
        "45",
        null,
        null,
        "45"
      ],
      "face_bottom": [
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "38",
        "60",
        "60",
        "60",
        "60",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "38",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "38",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60"
      ]
    },
    "objects": [
      {
        "p_id": 1,
        "sprite_id": 16,
        "left": 230,
        "top": 870,
        "z": -300,
        "rx": 0,
        "ry": 0,
        "rz": 326,
        "scale": 4
      },
      {
        "p_id": 2,
        "sprite_id": 1,
        "left": 361,
        "top": 881,
        "z": -17,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 3,
        "sprite_id": 1,
        "left": 1986,
        "top": 877,
        "z": 0,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 4,
        "sprite_id": 16,
        "left": 1541,
        "top": 895,
        "z": -300,
        "rx": 0,
        "ry": 173,
        "rz": 326,
        "scale": 4
      }
    ],
    "npcs": [
      {
        "n_id": 1,
        "sprite_id": 1,
        "left": 450,
        "top": 874,
        "z": 0,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1,
        "portrait_left": -57,
        "portrait_top": 9,
        "portrait_scaleX": 1,
        "dialogue": "hello world"
      }
    ],
    "treasure_boxes": [
      {
        "t_id": 1,
        "sprite_id": 5,
        "left": 563,
        "top": 883,
        "opened": false,
        "content_type": "item",
        "content_id": 0
      }
    ],
    "enemy_encounters": [
      {
        "encounter_id": 0,
        "front_position": 2,
        "mid_1": 0,
        "mid_2": 0,
        "back_1": null,
        "back_2": 1,
        "back_3": null,
        "rate": "common"
      },
      {
        "encounter_id": 0,
        "front_position": 7,
        "mid_1": 0,
        "mid_2": 0,
        "back_1": 1,
        "back_2": 19,
        "back_3": 16,
        "rate": "ultra_rare"
      },
      {
        "encounter_id": 0,
        "front_position": 2,
        "mid_1": 3,
        "mid_2": null,
        "back_1": null,
        "back_2": null,
        "back_3": null,
        "rate": "common"
      },
      {
        "encounter_id": 0,
        "front_position": null,
        "mid_1": null,
        "mid_2": null,
        "back_1": null,
        "back_2": 1,
        "back_3": null,
        "rate": "common"
      },
      {
        "encounter_id": 0,
        "front_position": 0,
        "mid_1": null,
        "mid_2": null,
        "back_1": 0,
        "back_2": 0,
        "back_3": 0,
        "rate": "common"
      },
      {
        "encounter_id": 0,
        "front_position": 0,
        "mid_1": 2,
        "mid_2": 3,
        "back_1": 5,
        "back_2": 1,
        "back_3": 4,
        "rate": "common"
      },
      {
        "encounter_id": 0,
        "front_position": 0,
        "mid_1": 18,
        "mid_2": 8,
        "back_1": null,
        "back_2": null,
        "back_3": null,
        "rate": "common"
      },
      {
        "encounter_id": 0,
        "front_position": 26,
        "mid_1": null,
        "mid_2": null,
        "back_1": null,
        "back_2": null,
        "back_3": null,
        "rate": "common"
      }
    ],
    "landmarks": [
      {
        "landmark_id": 1,
        "sprite_id": 0,
        "left": 60,
        "top": 812
      }
    ]
  },
  {
    "id": 5,
    "name": "mid",
    "size": "mid",
    "desc": "mid",
    "background": "2",
    "faces": {
      "face_back": [],
      "face_left": [],
      "face_right": [],
      "face_top": [],
      "face_bottom": [
        null,
        null,
        null,
        "16",
        "16",
        "16",
        null,
        null,
        null,
        null,
        null,
        null,
        "16",
        "16",
        "16",
        null,
        null,
        null,
        null,
        null,
        null,
        "16",
        "16",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "16",
        "16"
      ]
    },
    "objects": [],
    "npcs": [
      {
        "n_id": 1,
        "sprite_id": 0,
        "left": 230,
        "top": 870,
        "z": -117,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 2,
        "portrait_left": 0,
        "portrait_top": 0,
        "portrait_scaleX": 1,
        "dialogue": ""
      }
    ],
    "treasure_boxes": [],
    "enemy_encounters": [],
    "landmarks": []
  },
  {
    "id": 6,
    "name": "New Level",
    "size": "mid",
    "desc": "A new Level",
    "background": "12",
    "faces": {
      "face_back": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "39",
        null,
        null,
        null,
        null,
        "39",
        null,
        null,
        null,
        "39",
        "39",
        null,
        null,
        null,
        null,
        "39",
        null,
        null,
        null,
        "39",
        "39",
        null,
        null,
        null,
        null,
        "39",
        null,
        null,
        null,
        "39",
        "38",
        "38",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "60"
      ],
      "face_left": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "5",
        "5",
        "5"
      ],
      "face_right": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "6",
        "6",
        null,
        null,
        null,
        null,
        "6",
        null,
        null,
        null,
        "95",
        "6",
        "5",
        null,
        null,
        null,
        "38",
        "38"
      ],
      "face_top": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "52",
        null,
        null,
        null,
        "52",
        null,
        null,
        null,
        "52",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "52",
        null,
        null,
        null,
        null,
        "52"
      ],
      "face_bottom": [
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60",
        "60"
      ]
    },
    "objects": [
      {
        "p_id": 1,
        "sprite_id": 16,
        "left": 232,
        "top": 909,
        "z": -300,
        "rx": 0,
        "ry": 0,
        "rz": 336,
        "scale": 4
      },
      {
        "p_id": 2,
        "sprite_id": 16,
        "left": 769,
        "top": 920,
        "z": -300,
        "rx": 0,
        "ry": 186,
        "rz": 323,
        "scale": 4
      }
    ],
    "npcs": [
      {
        "n_id": 1,
        "sprite_id": 1,
        "left": 537,
        "top": 874,
        "z": 14,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1,
        "portrait_left": -51,
        "portrait_top": 0,
        "portrait_scaleX": 1,
        "dialogue": "Hello World..."
      }
    ],
    "treasure_boxes": [
      {
        "t_id": 1,
        "sprite_id": 5,
        "left": 334,
        "top": 880,
        "opened": false,
        "content_type": "weapon",
        "content_id": 11
      }
    ],
    "enemy_encounters": [
      {
        "encounter_id": 0,
        "front_position": 14,
        "mid_1": 2,
        "mid_2": 2,
        "back_1": null,
        "back_2": 1,
        "back_3": null,
        "rate": "common"
      }
    ],
    "landmarks": [
      {
        "landmark_id": 1,
        "sprite_id": 0,
        "left": 89,
        "top": 847
      }
    ]
  },
  {
    "id": 7,
    "name": "Test Room Two",
    "size": "mid",
    "desc": "second test",
    "background": "3",
    "faces": {
      "face_back": [
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "24",
        "31",
        "31",
        "31",
        "31",
        "31",
        "31",
        "31",
        "31",
        "31",
        "31",
        "15"
      ],
      "face_left": [
        "24",
        "24",
        "24",
        null,
        null,
        "24",
        "24",
        "24",
        null,
        null,
        "24",
        "24",
        "24",
        null,
        null,
        "31",
        "31",
        "31"
      ],
      "face_right": [
        null,
        null,
        "24",
        "24",
        "24",
        null,
        null,
        "24",
        "24",
        "24",
        null,
        null,
        "24",
        "24",
        "24",
        null,
        null,
        "31",
        "31",
        "31",
        null,
        null,
        null,
        "15",
        "15"
      ],
      "face_top": [
        "26",
        "27",
        "26",
        "26",
        "27",
        "26",
        "26",
        "27",
        "26",
        "26",
        "26",
        "27",
        "26",
        "26",
        "27",
        "26",
        "26",
        "27",
        "26",
        "26",
        "26",
        "27",
        "26",
        "26",
        "27",
        "26",
        "26",
        "27",
        "26",
        "26",
        "26",
        "27",
        "26",
        "26",
        "27",
        "26",
        "26",
        "27",
        "26",
        "26",
        "26",
        "27",
        "26",
        "26",
        "27",
        "26",
        "26",
        "27",
        "26",
        "26"
      ],
      "face_bottom": [
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15",
        "15"
      ]
    },
    "objects": [
      {
        "p_id": 2,
        "sprite_id": 14,
        "left": 600,
        "top": 850,
        "z": -300,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1.4
      },
      {
        "p_id": 3,
        "sprite_id": 14,
        "left": -60,
        "top": 853,
        "z": 0,
        "rx": 0,
        "ry": 84,
        "rz": 0,
        "scale": 1.4
      },
      {
        "p_id": 4,
        "sprite_id": 11,
        "left": -21,
        "top": 593,
        "z": -185,
        "rx": 150,
        "ry": 145,
        "rz": 0,
        "scale": 1
      }
    ],
    "npcs": [
      {
        "n_id": 1,
        "sprite_id": 1,
        "left": 906,
        "top": 877,
        "z": 0,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1,
        "portrait_left": 0,
        "portrait_top": 0,
        "portrait_scaleX": 1,
        "dialogue": ""
      }
    ],
    "treasure_boxes": [
      {
        "t_id": 1,
        "sprite_id": 0,
        "left": 313,
        "top": 880,
        "opened": false,
        "content_type": "weapon",
        "content_id": 6
      },
      {
        "t_id": 2,
        "sprite_id": 0,
        "left": 766,
        "top": 880,
        "opened": true,
        "content_type": "weapon",
        "content_id": 2
      }
    ],
    "enemy_encounters": [
      {
        "encounter_id": 0,
        "front_position": 0,
        "mid_1": null,
        "mid_2": null,
        "back_1": 5,
        "back_2": 1,
        "back_3": 5,
        "rate": "common"
      },
      {
        "encounter_id": 0,
        "front_position": 0,
        "mid_1": 0,
        "mid_2": 0,
        "back_1": null,
        "back_2": 1,
        "back_3": null,
        "rate": "uncommon"
      },
      {
        "encounter_id": 0,
        "front_position": null,
        "mid_1": 2,
        "mid_2": 2,
        "back_1": null,
        "back_2": 3,
        "back_3": null,
        "rate": "common"
      }
    ],
    "landmarks": [
      {
        "landmark_id": 2,
        "sprite_id": 0,
        "left": 0,
        "top": 920,
        "exit_type": "left",
        "destination_type": "to_world_map",
        "destination_to": "teleport:823"
      },
      {
        "landmark_id": 3,
        "sprite_id": 0,
        "left": 595,
        "top": 920,
        "exit_type": "up",
        "destination_type": "to_level",
        "destination_to": "8",
        "destination_landmark_id": "1"
      }
    ]
  },
  {
    "id": 8,
    "name": "creepyRoom",
    "size": "small",
    "desc": "test within a test",
    "background": "12",
    "faces": {
      "face_back": [
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "31",
        "31",
        "31",
        "31",
        "31"
      ],
      "face_left": [
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "31",
        "31",
        "31",
        "31",
        "31"
      ],
      "face_right": [
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "25",
        "31",
        "31",
        "31",
        "31",
        "31"
      ],
      "face_top": [
        "26",
        "26",
        "27",
        "26",
        "26",
        "26",
        "26",
        "27",
        "26",
        "26",
        "26",
        "26",
        "27",
        "26",
        "26",
        "26",
        "26",
        "27",
        "26",
        "26",
        "26",
        "26",
        "27",
        "26",
        "26"
      ],
      "face_bottom": [
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16",
        "16"
      ]
    },
    "objects": [
      {
        "p_id": 1,
        "sprite_id": 26,
        "left": 230,
        "top": 870,
        "z": -123,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 2,
        "sprite_id": 29,
        "left": 33,
        "top": 920,
        "z": 0,
        "rx": 80,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 3,
        "sprite_id": 29,
        "left": 111,
        "top": 920,
        "z": 119,
        "rx": 83,
        "ry": 0,
        "rz": 69,
        "scale": 1
      },
      {
        "p_id": 4,
        "sprite_id": 29,
        "left": 230,
        "top": 920,
        "z": 224,
        "rx": 83,
        "ry": 183,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 5,
        "sprite_id": 10,
        "left": -9,
        "top": 617,
        "z": -300,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 0.5
      },
      {
        "p_id": 6,
        "sprite_id": 29,
        "left": 419,
        "top": 920,
        "z": 32,
        "rx": 80,
        "ry": 0,
        "rz": 34,
        "scale": 1
      }
    ],
    "npcs": [],
    "treasure_boxes": [],
    "enemy_encounters": [],
    "landmarks": [
      {
        "landmark_id": 1,
        "sprite_id": 0,
        "left": 230,
        "top": 920,
        "exit_type": "down",
        "destination_type": "to_level",
        "destination_to": "7",
        "destination_landmark_id": "3"
      }
    ]
  },
  {
    "id": 9,
    "name": "Root",
    "size": "mid",
    "desc": "New game first room.",
    "background": "12",
    "faces": {
      "face_back": [
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "0"
      ],
      "face_left": [],
      "face_right": [],
      "face_top": [
        null,
        "95",
        null,
        null,
        "0",
        null,
        null,
        null,
        null,
        null,
        null,
        "0",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        "0"
      ],
      "face_bottom": [
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "38",
        "38",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "38",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "38",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0",
        "0"
      ]
    },
    "objects": [
      {
        "p_id": 1,
        "sprite_id": 90,
        "left": 230,
        "top": 825,
        "z": -160,
        "rx": 26,
        "ry": 0,
        "rz": 0,
        "scale": 2
      }
    ],
    "npcs": [],
    "treasure_boxes": [],
    "enemy_encounters": [],
    "landmarks": []
  },
  {
    "id": 10,
    "name": "RootMatrix",
    "size": "small",
    "desc": "Room 0",
    "background": "12",
    "faces": {
      "face_back": [
        "135",
        "135",
        "135",
        "135",
        "135",
        "135",
        "135",
        "135",
        "115",
        "135",
        "115",
        null,
        null,
        null,
        "135",
        "134",
        "95",
        null,
        null,
        "134",
        "38"
      ],
      "face_left": [
        "95",
        "95",
        "95",
        "95",
        null,
        "95",
        "95",
        "95",
        "95",
        null,
        "95",
        "95",
        "95",
        "115",
        null,
        "95",
        "95",
        "95",
        "95"
      ],
      "face_right": [
        null,
        "95",
        "95",
        "95",
        "95",
        null,
        "95",
        "115",
        "95",
        "95",
        null,
        "95",
        "95",
        "95",
        "95",
        null,
        "95",
        "95",
        "95",
        "95"
      ],
      "face_top": [
        "95",
        "95",
        "95",
        "95",
        "95",
        "122",
        "122",
        "122",
        "122",
        "122",
        "122",
        "122",
        "122",
        "122",
        "122",
        "122",
        "122",
        "122",
        "122",
        "122",
        "122",
        "122",
        "122",
        "122",
        "122"
      ],
      "face_bottom": [
        null,
        "95",
        "95",
        null,
        null,
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38",
        "38"
      ]
    },
    "objects": [
      {
        "p_id": 1,
        "sprite_id": 144,
        "left": 2,
        "top": 989,
        "z": 181,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 2,
        "sprite_id": 144,
        "left": 121,
        "top": 990,
        "z": 179,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 3,
        "sprite_id": 144,
        "left": 241,
        "top": 992,
        "z": 178,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1.04
      },
      {
        "p_id": 4,
        "sprite_id": 144,
        "left": 361,
        "top": 989,
        "z": 181,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 5,
        "sprite_id": 144,
        "left": 480,
        "top": 990,
        "z": 179,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1.02
      },
      {
        "p_id": 6,
        "sprite_id": 144,
        "left": 242,
        "top": 930,
        "z": -359,
        "rx": 270,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 7,
        "sprite_id": 144,
        "left": 242,
        "top": 930,
        "z": -481,
        "rx": 270,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 8,
        "sprite_id": 14,
        "left": 242,
        "top": 890,
        "z": -536,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 2
      },
      {
        "p_id": 9,
        "sprite_id": 106,
        "left": 118,
        "top": 870,
        "z": -300,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 10,
        "sprite_id": 106,
        "left": 187,
        "top": 870,
        "z": -355,
        "rx": 0,
        "ry": 81,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 11,
        "sprite_id": 107,
        "left": 361,
        "top": 870,
        "z": -299,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 12,
        "sprite_id": 107,
        "left": 294,
        "top": 870,
        "z": -349,
        "rx": 0,
        "ry": -81,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 13,
        "sprite_id": 112,
        "left": 119,
        "top": 749,
        "z": -288,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 14,
        "sprite_id": 112,
        "left": 187,
        "top": 750,
        "z": -355,
        "rx": 0,
        "ry": 81,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 15,
        "sprite_id": 113,
        "left": 294,
        "top": 751,
        "z": -355,
        "rx": 0,
        "ry": -81,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 16,
        "sprite_id": 113,
        "left": 360,
        "top": 750,
        "z": -288,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 17,
        "sprite_id": 145,
        "left": 240,
        "top": 776,
        "z": -538,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 18,
        "sprite_id": 145,
        "left": 238,
        "top": 656,
        "z": -534,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 19,
        "sprite_id": 119,
        "left": 241,
        "top": 479,
        "z": 179,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 20,
        "sprite_id": 119,
        "left": 121,
        "top": 479,
        "z": 179,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 21,
        "sprite_id": 119,
        "left": 361,
        "top": 479,
        "z": 179,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 22,
        "sprite_id": 119,
        "left": 2,
        "top": 480,
        "z": 182,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 23,
        "sprite_id": 119,
        "left": 480,
        "top": 480,
        "z": 181,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 24,
        "sprite_id": 6,
        "left": 242,
        "top": 663,
        "z": -299,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 25,
        "sprite_id": 102,
        "left": 600,
        "top": 630,
        "z": 60,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 26,
        "sprite_id": 102,
        "left": 602,
        "top": 690,
        "z": 0,
        "rx": 90,
        "ry": 0,
        "rz": 0,
        "scale": 1
      },
      {
        "p_id": 27,
        "sprite_id": 102,
        "left": -141,
        "top": 750,
        "z": 138,
        "rx": 0,
        "ry": 0,
        "rz": 0,
        "scale": 1.06
      }
    ],
    "npcs": [],
    "treasure_boxes": [],
    "enemy_encounters": [],
    "landmarks": []
  }
]